<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rcl" nsURI="http://cs.york.ac.uk/eng2/rcl" nsPrefix="r">
  <eClassifiers xsi:type="ecore:EEnum" name="SlotType">
    <eLiterals name="integer"/>
    <eLiterals name="double" value="1"/>
    <eLiterals name="string" value="2"/>
    <eLiterals name="timestamp" value="3"/>
    <eLiterals name="long_" value="4" literal="long"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SlotPart">
    <eLiterals name="body"/>
    <eLiterals name="key" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeUnit">
    <eLiterals name="seconds"/>
    <eLiterals name="minutes" value="1"/>
    <eLiterals name="hours" value="2"/>
    <eLiterals name="days" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topics" upperBound="-1"
        eType="#//Topic" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" lowerBound="1"
        upperBound="-1" eType="#//Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="produces" upperBound="-1"
        eType="#//Topic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slots" lowerBound="1" upperBound="-1"
        eType="#//Slot" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SlotType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="part" eType="#//SlotPart"
        defaultValueLiteral="body"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="period" lowerBound="1"
        eType="#//TimePeriod" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopicTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic" lowerBound="1" eType="#//Topic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimePeriod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="#//TimeUnit"/>
  </eClassifiers>
</ecore:EPackage>
