#

pluginName = Reactive Model Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Model_type = Model
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Unknown_feature = Unspecified

_UI_Component_type = Component
_UI_Topic_type = Topic
_UI_Slot_type = Slot
_UI_Trigger_type = Trigger
_UI_TimeTrigger_type = Time Trigger
_UI_TopicTrigger_type = Topic Trigger
_UI_TimePeriod_type = Time Period
_UI_Model_components_feature = Components
_UI_Model_topics_feature = Topics
_UI_Component_name_feature = Name
_UI_Component_triggers_feature = Triggers
_UI_Component_produces_feature = Produces
_UI_Topic_name_feature = Name
_UI_Topic_slots_feature = Slots
_UI_Slot_name_feature = Name
_UI_Slot_type_feature = Type
_UI_Slot_part_feature = Part
_UI_TimeTrigger_period_feature = Period
_UI_TopicTrigger_topic_feature = Topic
_UI_TimePeriod_value_feature = Value
_UI_TimePeriod_unit_feature = Unit
_UI_SlotType_integer_literal = integer
_UI_SlotType_double_literal = double
_UI_SlotType_string_literal = string
_UI_SlotType_timestamp_literal = timestamp
_UI_SlotType_long__literal = long
_UI_SlotPart_body_literal = body
_UI_SlotPart_key_literal = key
_UI_TimeUnit_seconds_literal = seconds
_UI_TimeUnit_minutes_literal = minutes
_UI_TimeUnit_hours_literal = hours
_UI_TimeUnit_days_literal = days
